# Generated by Django 6.0 on 2025-12-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sweets',
        ),
    ]
